# Generated by Django 3.1.4 on 2022-02-19 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='abonement_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='all_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2022, 2, 19)),
        ),
        migrations.AddField(
            model_name='attendance',
            name='day',
            field=models.CharField(choices=[('Monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница'), ('Saturday', 'Суббота'), ('Sunday', 'Воскресенье')], default='Not Set', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='first_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='location',
            field=models.CharField(choices=[('POZNYAKI', 'Позняки'), ('TROYESCHINA', 'Троещина'), ('DARNITSA', 'Дарница'), ('LESNAYA', 'Лесная'), ('PECHERSK', 'Печерск'), ('KLOVSKA', 'Кловская'), ('SHULYAVSKA', 'Шулявская'), ('OBOLON', 'Оболонь')], default='Not Set', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.CharField(choices=[('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00')], default='Not Set', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='trainer',
            field=models.CharField(choices=[('Venger', 'Венгер'), ('Svistunov', 'Свистунов'), ('Kornev', 'Корнев'), ('Alekseyenko', 'Алексеенко'), ('Kovalevsky', 'Ковалевский'), ('Shoferenko', 'Шоференко'), ('Galitsky', 'Галицкий'), ('Vorontsov', 'Воронцов'), ('Karpenko', 'Карпенко'), ('Shkrob', 'Шкроб'), ('Sarkisyan', 'Саркисян'), ('Volskiy', 'Вольский'), ('Zaytsev', 'Зайцев'), ('Petrovskiy', 'Петровский'), ('Doroshenko', 'Дорошенко'), ('Ray', 'Рай')], default='Not Set', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 19, 14, 8, 59, 999356)),
        ),
        migrations.AddField(
            model_name='payment',
            name='location',
            field=models.CharField(choices=[('POZNYAKI', 'Позняки'), ('TROYESCHINA', 'Троещина'), ('DARNITSA', 'Дарница'), ('LESNAYA', 'Лесная'), ('PECHERSK', 'Печерск'), ('KLOVSKA', 'Кловская'), ('SHULYAVSKA', 'Шулявская'), ('OBOLON', 'Оболонь')], default='Not Set', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 19, 14, 8, 59, 999557)),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('month', 'Месяц'), ('one_time', 'Разовый'), ('part_month', 'Часть месяца'), ('personal', 'Персональный'), ('personal_pakage', 'Персональный пакет')], default='Not Set', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='trainer',
            field=models.CharField(choices=[('Venger', 'Венгер'), ('Svistunov', 'Свистунов'), ('Kornev', 'Корнев'), ('Alekseyenko', 'Алексеенко'), ('Kovalevsky', 'Ковалевский'), ('Shoferenko', 'Шоференко'), ('Galitsky', 'Галицкий'), ('Vorontsov', 'Воронцов'), ('Karpenko', 'Карпенко'), ('Shkrob', 'Шкроб'), ('Sarkisyan', 'Саркисян'), ('Volskiy', 'Вольский'), ('Zaytsev', 'Зайцев'), ('Petrovskiy', 'Петровский'), ('Doroshenko', 'Дорошенко'), ('Ray', 'Рай')], default='Not Set', max_length=20),
        ),
    ]
